version: "3"

services:
  web:
    image: nginx:1.17.4-alpine
    volumes:
      - ./website:/usr/share/nginx/html
    ports:
      - "80"
    environment:
      - NGINX_PORT=80
      
  redirect:
    image: nginx:1.17.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "4000:4000"